spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    check-template-location: true
    mode: HTML
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/teachonline?userUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  type-aliases-package: com.zhanc.teachonline.entity


server:
  port: 8091

logging:
  level:
    com.zhanc.teachonline.dao: debug

swagger:
  enable: true

file:
  upload:
    path: D://Pictures/BlogAdmin/ArticleImg/
    virtual-path: /article/img/.