spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    check-template-location: true
    mode: HTML
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/teachonline?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 20MB

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  type-aliases-package: com.zhanc.teachonline.entity


server:
  port: 8091


logging:
  level:
    com.zhanc.teachonline.dao: debug

swagger:
  enable: true

file:
  upload:
    path: D://Pictures/TeachOnline/media/
    virtual-path: media/

management:
  server:
    port: 8092
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    env:
      enabled: false
